version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: tododb
      POSTGRES_PASSWORD: tododb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
